apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: microservices-one
build:
  local:
    push: true
  artifacts:
    - image: arnavchhabra/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: arnavchhabra/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: arnavchhabra/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: arnavchhabra/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: arnavchhabra/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: arnavchhabra/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/client-depl.yaml
      - ./infra/k8s/comment-depl.yaml
      - ./infra/k8s/comment-srv.yaml
      - ./infra/k8s/event-bus-depl.yaml
      - ./infra/k8s/ingress-srv.yaml
      - ./infra/k8s/moderation-depl.yaml
      - ./infra/k8s/post-srv.yaml
      - ./infra/k8s/posts-depl.yaml
      - ./infra/k8s/query-depl.yaml
      - ./infra/k8s/query-srv.yaml
